#!/usr/bin/env bash
# Install nginx server
apt-get update
apt-get install nginx -y
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
command="\\\n\t# Redirection\n\trewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/server_name _;/ a $command" /etc/nginx/sites-available/default
/etc/init.d/nginx restart
