#!/usr/bin/env bash
# redirection
sudo apt update -y
sudo apt-get install nginx -y
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i "/listen 80 default_server;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent;" /etc/nginx/sites-available/default;
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
string_404="server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$string_404/" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
