#!/usr/bin/env bash
# prints string 20 times with a loop
i=1
while [ $i -le 20 ]
do
    case $i in
        4) echo $i
            echo bad luck from China
            ((i++))
            ;;
        9) echo $i
            echo bad luck from Japan
            ;;
        17) echo $i
            echo bad luck from Italy
            ((i++))
            ;;
    esac
    echo $i
((i++))
done
