#!/usr/bin/env bash
# give information about a file
FILE=holbertonschool
if [ -e "$FILE"  -o  -d "$FILE" ]
then
    echo "$FILE file exists"
    if [ -s "$FILE" ]
    then
	echo "$FILE file is not empty"
    else
	echo "$FILE file is empty"
    fi
    if [ -f "$FILE" ]
    then
	echo "$FILE is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
